### ISSUE TITLE
Commenters seem to be broken

### ISSUE THREAD

**Issue by razki** [timgrossmann/instagram-profilecrawl#154]
Afternoon,

When scraping the profiles it seems that there is an issue when trying to get the commenters of a particular post:

ERROR [2019-07-31 15:22:58] ERROR something went wrong getting user_commented
ERROR [2019-07-31 15:22:58] ERROR something went wrong getting comment

Probably a duplicate of #152 But creating another Issue to surface it

**Comment by itsdante** [comment]
hey, I fixed it actually but I'm still trying to fix the others, so go to utils/extractor_posts.py. change all the user_commented[3] from this line to user_commented[1]

`
user_commented = comm.find_element_by_tag_name('a').get_attribute("href").split('/')
user_commented_list.append(user_commented[3])
`

**Comment by lamoo** [comment]
> hey, I fixed it actually but I'm still trying to fix the others, so go to utils/extractor_posts.py. change all the user_commented[3] from this line to user_commented[1]
> 
> `user_commented = comm.find_element_by_tag_name('a').get_attribute("href").split('/') user_commented_list.append(user_commented[3])`

Hi, Thank's for this solution, but same comments still broken. 
Did you have solution?

**Comment by itsdante** [comment]
> > hey, I fixed it actually but I'm still trying to fix the others, so go to utils/extractor_posts.py. change all the user_commented[3] from this line to user_commented[1]
> > `user_commented = comm.find_element_by_tag_name('a').get_attribute("href").split('/') user_commented_list.append(user_commented[3])`
> 
> Hi, Thank's for this solution, but same comments still broken.
> Did you have solution?

I actually fixed it by changing it to 1, I currently do not have any problem. Just so we're clear, did you login to your account before scraping the comments ? and is the account you're scraping public ?
